### ISSUE TITLE
The mod is only saving on Game load

### ISSUE THREAD

**Issue by z3r0b00t3r** [ntaklive/BackupMod#1]
The mod is only saving backups on game load.
Even with EAC disabled i dont get the chat notifications of the backups every 10min (as default by the json file) not do i get the files themselves.

**Comment by ntaklive** [comment]
I apologize for the inconvenience.
https://github.com/ntaklive/BackupMod/releases/tag/v1.0.2

**Comment by z3r0b00t3r** [comment]
no need to apologise bro. 
This is by far the best and most usefull mod for 7D2D.

I'm glad i could help you by reporting the bug ;)
