### ISSUE TITLE
Question(s)

### ISSUE THREAD

**Issue by Fireworkstars46** [ntaklive/BackupMod#10]
Does the mod have a setting so I can have it at 10 backups and delete the oldest ones when a new one comes in?

**Comment by ntaklive** [comment]
Yep. Use the "BackupsLimit" option that located in the "General" section of the settings.json file

**Comment by Fireworkstars46** [comment]
As for loading the backup, how exactly would I load it?

**Comment by ntaklive** [comment]
> As for loading the backup, how exactly would I load it?

Just use commands. You can find them in readme.
/bp list
then
/bp restore '**world id**' '**save id**' '**backup id**'

**Comment by Fireworkstars46** [comment]
Also for the backup max limit (the feature where it has a limit I set to (for example I set it to 10, it will delete the oldest one when the 11th one comes in)), when it deletes the old one etc, does it clear the cache too or would it still use more pc storage?

**Comment by ntaklive** [comment]
> Also for the backup max limit (the feature where it has a limit I set to (for example I set it to 10, it will delete the oldest one when the 11th one comes in)), when it deletes the old one etc, does it clear the cache too or would it still use more pc storage?

I'm not quite sure what you mean by "cache", but the mod removes the oldest backup from the file system (I mean .zip file).

**Comment by Fireworkstars46** [comment]
My next question I have is. Does it support multiplayer? Like my brother hosts his world on lan for me to join and if he adds it to his game and I join, would it work or no?

**Comment by ntaklive** [comment]
> My next question I have is. Does it support multiplayer? Like my brother hosts his world on lan for me to join and if he adds it to his game and I join, would it work or no?

Yes, all backups will be saved on his computer

**Comment by Fireworkstars46** [comment]
Also can I do manual backups instead of automatic ones?

**Comment by Fireworkstars46** [comment]
Also is there new version of the mod on A20?

**Comment by Fireworkstars46** [comment]
Are you still active?

**Comment by Fireworkstars46** [comment]
Anyone active still?

**Comment by Fireworkstars46** [comment]
What about my questions?

**Comment by ntaklive** [comment]
> Also can I do manual backups instead of automatic ones?

You can use the 'bp' command in the game console.

> Also is there new version of the mod on A20?

[v2.1.3](https://github.com/ntaklive/BackupMod/releases/tag/v2.1.3) is the last version for Alpha 20. And I don't plan to update the mod for older versions of the game at this moment.

> Anyone active still?

Yeah, I'm back from the army.

> What about my questions?

I thought they were no longer relevant. It's been a long time.

**Comment by Fireworkstars46** [comment]
Also does the mod need internet to work or can it work offline?

**Comment by rautamiekka** [comment]
> Also does the mod need internet to work

No. You can see the code and easily tell it's too simple to even do anything with an Internet connection.

**Comment by Fireworkstars46** [comment]
Is there discord?

**Comment by ntaklive** [comment]
> Is there discord?

nope

**Comment by Fireworkstars46** [comment]
Would it be possible for you to join a current discord I have already?

**Comment by ntaklive** [comment]
Yep, no problem

**Comment by Fireworkstars46** [comment]
The server I'm on is this one https://discord.gg/zuFRhjx5zH
