### ISSUE TITLE
Question(s)

### ISSUE THREAD

**Issue by jillv46** [ntaklive/BackupMod#11]
Is there a setting to make it so when I do the manual backup the time for the auto ones reset? Like I want my auto ones to happen every 30 mins but at 3:30 pm even then 4 pm even then 4:30 even etc but it slowly gets more and more off and I got to a point that it was like doing the backups at 1-2 mins late. Is there a way for me so when I do the backup at 3:30 pm even it would fix the delay and reset the thing again or? Like I see this (ResetDelayTimerAfterManualBackup) but idk if it's what I need or not

**Comment by jillv46** [comment]
Also I'm getting this error now when trying to create a backup![image](https://github.com/ntaklive/BackupMod/assets/29643271/752323f3-730b-4ed0-bcc6-0e6ea6cbecfe)

**Comment by jillv46** [comment]
@ntaklive ^

**Comment by ntaklive** [comment]
> Is there a setting to make it so when I do the manual backup the time for the auto ones reset? Like I want my auto ones to happen every 30 mins but at 3:30 pm even then 4 pm even then 4:30 even etc but it slowly gets more and more off and I got to a point that it was like doing the backups at 1-2 mins late. Is there a way for me so when I do the backup at 3:30 pm even it would fix the delay and reset the thing again or? Like I see this (ResetDelayTimerAfterManualBackup) but idk if it's what I need or not

I'll fix that little bit later this month

> Also I'm getting this error now when trying to create a backup![image](https://private-user-images.githubusercontent.com/29643271/313855339-752323f3-730b-4ed0-bcc6-0e6ea6cbecfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3OTk5MjcsIm5iZiI6MTczMTc5OTYyNywicGF0aCI6Ii8yOTY0MzI3MS8zMTM4NTUzMzktNzUyMzIzZjMtNzMwYi00ZWQwLWJjYzYtMGU2ZWE2Y2JlY2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDIzMjcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYzBhZWU5MWY5ZmY4NTFhN2JlMmFjZTRiNThlYjVlYjgzNjIxMGExNDMwZWJiYWFlZGQ4ODFiOTI4M2IxYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vewc7o3b_MrSN7AMg0LDp1rtoST_FnHndl80otn8aUM)

I can't do anything with this error. You should also have sent me the content of the broken manifest.json file

> @ntaklive ^

I was in the army)
