### ISSUE TITLE
Can't run on A21b16

### ISSUE THREAD

**Issue by woshigenm** [ntaklive/BackupMod#12]
[output_log_client.txt](https://github.com/ntaklive/BackupMod/files/12795836/output_log_client.txt)

**Comment by ntaklive** [comment]
From your log:

> 023-10-04T02:30:00 9.622 ERR [MODS] Failed initializing ModAPI instance on mod 'ntaklive_BackupMod' from DLL 'BackupMod.dll'
> 2023-10-04T02:30:00 9.624 EXC Illegal characters in path.
>   at System.IO.Path.IsPathRooted (System.String path) [0x0001b] in <03bd9b261dff4c2b8b568aca27f561b2>:0 
>   at System.IO.Path.InsecureGetFullPath (System.String path) [0x000bd] in <03bd9b261dff4c2b8b568aca27f561b2>:0 
>   at System.IO.Path.GetFullPath (System.String path) [0x00000] in <03bd9b261dff4c2b8b568aca27f561b2>:0 
>   at System.IO.DirectoryInfo..ctor (System.String path) [0x00006] in <03bd9b261dff4c2b8b568aca27f561b2>:0 
>   at (wrapper remoting-invoke-with-check) System.IO.DirectoryInfo..ctor(string)
>   at BackupMod.Services.Filesystem.DirectoryService.Create (System.String path) [0x00000] in <12718f26315e49aaba0fac0f59cde1bc>:0 
>   at BackupMod.Modules.Common.CommonModule.CreateRequiredFolders () [0x00023] in <12718f26315e49aaba0fac0f59cde1bc>:0 
>   at BackupMod.Modules.Common.CommonModule.InitializeModule (System.IServiceProvider provider) [0x0005d] in <12718f26315e49aaba0fac0f59cde1bc>:0 
>   at BackupMod.Modules.Base.ModuleExtensions+<>c__DisplayClass1_0.<InitializeModules>b__0 (BackupMod.Modules.Base.IModule module) [0x00000] in <12718f26315e49aaba0fac0f59cde1bc>:0 
>   at BackupMod.Modules.Base.EnumerableExtensions.ForEach[T] (System.Collections.Generic.IEnumerable`1[T] collection, System.Action`1[T] action) [0x00010] in <12718f26315e49aaba0fac0f59cde1bc>:0 
>   at BackupMod.Modules.Base.ModuleExtensions.InitializeModules (IModApi _, System.IServiceProvider provider) [0x00018] in <12718f26315e49aaba0fac0f59cde1bc>:0 
>   at BackupMod.ModApi.InitMod (Mod _modInstance) [0x0002e] in <12718f26315e49aaba0fac0f59cde1bc>:0 
>   at (wrapper dynamic-method) Mod.DMD<Mod::InitModCode>(Mod)
> UnityEngine.StackTraceUtility:ExtractStringFromException(Object)
> Log:Exception(Exception)
> Mod:DMD<Mod::InitModCode>(Mod)
> CustomModManager.Mod.Mod:Initialize() (at /var/jenkins_home/workspace/ModManager_stable/Source/Mod/Mod.cs:126)
> CustomModManager.Mod.Mod:Load() (at /var/jenkins_home/workspace/ModManager_stable/Source/Mod/Mod.cs:118)
> CustomModManager.Mod.Mod_InitModCode_Patch:Postfix() (at /var/jenkins_home/workspace/ModManager_stable/Source/Mod/ModLoaderPatches.cs:45)
> Mod:DMD<Mod::InitModCode>(Mod)
> ModManager:LoadMods()
> GameManager:Awake()

It seems that the mod cannot create required directories because of illegal characters in some path. Did you configure the mod somehow? I guess it may be an invalid path configuration

**Comment by woshigenm** [comment]
I checked my path configuration and found that when I changed the CustomBackupsFolder to the D drive the application threw an error with illegal characters in the path. However, when I changed the CustomBackupsFolder back to the C drive, it worked correctly. I'm not sure why.
