### ISSUE TITLE
JSON format incorrect

### ISSUE THREAD

**Issue by SageJJ** [ntaklive/BackupMod#3]
Backup is not listening to the settings.json file for location and frequency of backups or archive, and when I start my server I get the attached error.  I have disabled EAC in the server settings before opening this issue, but it still persists.

![image](https://user-images.githubusercontent.com/109370004/179281519-2427ac12-0176-4619-9696-502fa8e272fd.png)

**Comment by rautamiekka** [comment]
It tells you exactly what's wrong. Use a JSON linter such as https://jsonlint.com/ to find exactly where the mentioned problem is, and read up `how to escape a character in json`.

<details>
  <summary>Spoilers</summary>
  
  ```
  \\
  ```
  
</details>

**Comment by SageJJ** [comment]
Thank you for the quick response and the link.  It turns out that the "commented out" section was causing the issue.  Deleting those fixed the issue.

**Comment by rautamiekka** [comment]
Yeah, JSON explicitly doesn't support comments, some apps work around with something like:
```json
{
    "#": "comment"
}
```
