### ISSUE TITLE
[v2.1.2] bp restore is not working in single game and main menu

### ISSUE THREAD

**Issue by steward2022** [ntaklive/BackupMod#6]
I met this message
[This command cannot executed on an active world save. Try to another parameters]

![image](https://user-images.githubusercontent.com/115856739/195968066-cc1e3b3c-3949-417f-9da4-d7fbc234e6e4.png)

![image](https://user-images.githubusercontent.com/115856739/195968105-3eb4f7c8-8d0b-4c2f-8c4b-80d7df253bd0.png)

**Comment by ntaklive** [comment]
Thanks for your report. Fixed in [2.1.3](https://github.com/ntaklive/BackupMod/releases/tag/v2.1.3)
