### ISSUE TITLE
AutoBackup.Delay option doesn't account for how long the actual backup takes

### ISSUE THREAD

**Issue by IanKemp** [ntaklive/BackupMod#9]
For example, I have `AutoBackup.Delay` set to `300` (5 minutes). Assume that an auto-backup happens at 17:00:00 and takes 20 seconds to complete.

What should happen is that the next auto-backup occurs at 17:05:00.
What actually happens is that it occurs at 17:05:20, because the previous backup took 20 seconds to complete.

If that second backup takes 30 seconds to complete, then the next backup will occur at 17:10:50, instead of 17:10:00.

With a minimal reading of the code, my suggestion is that `AutoBackupProcess.BackupAsync` should return a `TimeSpan` of how long the actual backup process took, and the `Task.Delay` call in `AutoBackupProcess.StartAsync` should change to wait for `_delay - (duration of previous BackupAsync call)` instead of just `_delay`.

**Comment by rautamiekka** [comment]
This could get especially bad if the process takes longer than the interval.
